### ISSUE TITLE
Cloning existing attributes from one type to another is broken

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#1033]
For specific interactions, I made a new poly type, and it doesn't seem to be populating the types I can copy attributes from correctly

![image (11)](https://user-images.githubusercontent.com/7937658/213694393-8f2bad97-3921-4320-9748-8100833c8bbe.png)

**Comment by ermbutler** [comment]
This was fixed in PR #1040 
https://github.com/cvisionai/tator/pull/1040/commits/1b7216b6b241baf30d71a540deb0d602fc1b53af
The data was either gotten right from the api request, or using the store value which came back as a map - it wasn't properly parsing the map which is why it sometimes appeared to work, and othertimes showed undefined.
