### ISSUE TITLE
Implement Change Log

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#172]
PSQL Table

pk | modifying user | modified_time | referenced object (Foreign Key) | change description (JSON object)

modifying user + referenced object and time are all 1st class columns. Change description is a json object so that it can be free-form based on the change. We could index these either in PSQL or even ES if we ever needed to search them by value.

An example change description would look like:
{"x": {"old": 3.5, "new": 4.2}, "y"..... } for a move

{"Species": {"old": "Lobster","new":"Fish"}}

We could explore nesting Attributes in an attributes object, if that made creation or analysis work easier.

Expected use-cases are to look at all changes to an object, all changes to all objects related to a media, time durations, etc. The actual change information for resizes and what have you are probably extraneous but are useful for attribute changes and likely not a big deal to store. We could think about some kind of timeout if we needed to.

**Comment by henxing** [comment]
It seems like the modifying user will be a standard `ForeignKey`, but we can handle referencing an arbitrary object by making use of the `GenericForeignKey` field type that `contenttypes` provides. As for the change description, I would make it the diff of the previous and current fields. For example:

```
old ={"Species": "Lobster", "Length": 31}
new = {"Species": "Cod", "Length": 31}
change_description = {"Species": "Lobster"}
```

That way it is possible to just merge the change description with the current object to get the previous object.

As for how to make use of the `ChangeLog` model, I think helper functions make sense, since this will have to be used in any of the rest endpoints with a `PATCH` operation. On the other hand, this may only apply to `Localization`s, which would make this something that only needed to exist in the localization detail view api and it would even negate the need for a generic foreign key.

**Comment by henxing** [comment]
After some discussion in slack, this will be implemented by adding a `change_log` field directly in the four entity types: `Localization`, `Media`, `State`, and `Leaf`. It will be a `JSONField` and be a list of changes, e.g.

```
[{
  old: [{
    name: "Species",
    value: "Lobster"
  }, {
    name: "Length",
    value: 31
  }],
  new: [{
    name: "Species",
    value: "Cod"
  }, {
    name: "Length",
    value: 31
  }],
  modified_by: <user_id>
  modified_datetime: <datetime>
}]
```

**Comment by henxing** [comment]
Ok, I created [ModelDiffMixin](https://github.com/cvisionai/tator/blob/dev/172_entity_type_change_log/main/models.py#L64) that can be added to any model and automate collection of the changes made to an object. Thinking about bulk updates, there are two possible approaches:

**Comment by henxing** [comment]
Ok, I created [ModelDiffMixin](https://github.com/cvisionai/tator/blob/dev/172_entity_type_change_log/main/models.py#L64) that can be added to any model and automate collection of the changes made to an object. Thinking about bulk updates, there are two possible approaches:

1. One `ChangeLog` record associated with multiple changed objects
2. Many `ChangeLog` records, each one associated with a single changed object

The first one would require a generic `ManyToMany` relationship, which could be achieved by using something like [django-generic-m2m](https://github.com/coleifer/django-generic-m2m). It would also assume that either the "old" state of all updated attributes was the same, since it would be a single record describing the change. The second would create one `ChangeLog` record for every object in the queryset, which might be a lot. Both of them have the same fundamental problem, though: they will not work with the mixin as it is currently implemented. The mixin works by storing the state of an object immediately after it is queried from the database and then comparing that to the current state of the object when asked for the diff. A less automated way could easily be crafted from the mixin that would allow for either of these to work, but there will be slightly more boilerplate to add to each change we want to capture.

**Comment by henxing** [comment]
Based on the discussion [in slack](https://cvisionai.slack.com/archives/CEQ6T1144/p1611949936115000), we'll create a `ChangeToObject` table to track the `ChangeLog` association with each object affected by a particular change. It'll have columns `ref_table`, which tells you the table the changed object belongs to, `ref_id`, the id of the changed object, and `change_id`, which can be a foreign key to the associated `ChangeLog` object.

As for the previous comments about the mixin not working with bulk changes, that still holds and there will be some refactoring to address that.
