### ISSUE TITLE
install.sh Django create superuser password unset with Django version 2.2.7

### ISSUE THREAD

**Issue by DougForrest** [cvisionai/tator#440]
Following the [Install Tator tutorial ](https://www.tator.io/tutorials/2021-03-29-install-tator/) create superuser fails to set password.

![image](https://user-images.githubusercontent.com/7332743/127071218-d74d4f4e-498c-4230-a658-b9ba1dd03114.png)

install.sh
```bash
# Create a superuser.
echo "Creating a superuser."
GUNICORN_POD=$(kubectl get pod -l app=gunicorn -o name | head -n 1 | sed 's/pod\///')
kubectl exec -it $GUNICORN_POD -- env DJANGO_SUPERUSER_PASSWORD=admin \
    python3 manage.py createsuperuser --username admin --email no-reply@cvisionai.com --noinput
```

Setting password via environmental variable is available in [Django version >3.0 ](https://docs.djangoproject.com/en/3.0/ref/django-admin/)tator is using version 2.2.7
![image](https://user-images.githubusercontent.com/7332743/127071314-d9cf3f2d-ddf6-4d5f-bf27-a203f0610c43.png)

**Comment by jrtcppv** [comment]
Thank you for the nice writeup and for bringing this to our attention. I have pushed a fix for this that sets the password in a separate command. It was tested on a fresh Ubuntu install. I will make a new release shortly so that the tutorial will work. Also, we will be merging in a branch with front end tests that should catch this type of error in the future.

**Comment by DougForrest** [comment]
Awesome thanks for fixing this and line 49 on install.sh as well! Hoping to get tator up and running for an annotation project it looks pretty cool.
