### ISSUE TITLE
Add support for cross origin images

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#576]
Images do not require special encoding so it would be nice if a `Media` object could be use a cross-origin URL rather than an S3 key.

**Comment by bctcvai** [comment]
Of note: the server these are sourced from will need an "allow_origin" to whatever server is running the Tator UI.

**Comment by bctcvai** [comment]
Let's set the COEP header to 'credentialless' now that is widely supported. That will allow usage of no-cors requests along side SharedMemoryBuffer usage.

**Comment by bctcvai** [comment]
The PR here: #1165 turns out not to address the technical issue. Data retreived from 'no-cors' requests can not be used in very many contexts, ones we end up using in the annotator.

Thus, to support accessing images from 3rd party servers a requirement that uses the "allow_origin" header, to allow for a CORs request, still stands.

Additionally logic here https://github.com/cvisionai/tator/blob/47d5d65ed74de546ee4270891202dbadb41cb85a/api/main/rest/media.py#L109-L111, should be adjusted to skip over any path that is not a key (likely by parsing with urlparse and looking at schema which would ring up as https://) -- this would prevent non-keys from being presigned via the backend. 

On import, we'd also have to not create `Resource` objects for resources that are not on our bucket(s).
