### ISSUE TITLE
Remove "OK" popup from Corrections view after edit

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#777]
When making edits on the "Corrections" view, an action-taken notification pops up which has to be clicked on to dismiss appears. This necessitates a user to have to make an extraneous mouse-movement + click, slowing down workflow.

Having an "OK" button that doesn't have any function beyond dismissing the notification is a bit counter productive. The notification should be similar to that found on the Localizations Analytics page and the Video Annotation view: just a pop-up with the salient information on the modified localizations what dismisses itself and doesn't interrupt workflow.

**Comment by ermbutler** [comment]
Hi @sbatchelder this has been brought up before related to our project settings page (uses same flow with "submit" rather than save on change, a confirm change in some cases, and then the success modal with summary and OK button) ---

For corrections, I am wondering would you want the option to skip confirmation next time, like "don't show again" on the confirmation popup? Or, is the main click problem the success with OK only?

Also, just some background / thought:

The success messages in both settings and here started down the path of modal because they potentially have more info that the lightbox in top right can display or a user may need time to read it. I would like to keep showing the success/fail i a consistent location, which may be the top right. I need to think about if there is a way to have a that same message box persist and then be dismissible in cases where more complicated result exists.

**Comment by ermbutler** [comment]
Success will now auto-fade --> This is live. Part of [Release 0.2.20](https://github.com/cvisionai/tator/releases/tag/0.2.20)
Bug fix for timing of fade on master.
