### ISSUE TITLE
Set as main track seems to lead to Page Unresponsive

### ISSUE THREAD

**Issue by jimmyfreese** [cvisionai/tator#811]
I've been able to get this to fairly reliably repeat where the page becomes unresponsive after I right click and 'set as main track'. Please see the attached screenshot.

I'm using the following on:
Linux cvision-tator-2 5.15.0-1017-azure #20~20.04.1-Ubuntu SMP Fri Aug 5 12:16:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Using the Azure instance specified in this tutorial:
Standard_D8s_v3
https://www.tator.io/docs/administrator-guide/install-examples/install-tator-on-an-azure-vm

<img width="1573" alt="Screen Shot 2022-08-12 at 5 06 24 PM" src="https://user-images.githubusercontent.com/111165068/184466119-a2405689-b456-49b6-b957-2c19e723877b.png">

**Comment by jimmyfreese** [comment]
Update: Another person in our company wasn't having this problem with 'set as main track'. He wasn't getting the unresponsive error that I was seeing. We will keep providing more information as we get it. It's possible this isn't a widespread issue.

**Comment by jrtcppv** [comment]
Thank you for opening the issue. We believe this may be caused by an issue that is fixed on `master`. Certain actions in 0.2.19 can cause the canvas to refresh rapidly, and depending on the client machine this may cause resource issues. Note that this is a front end issue, so would not be affected by your use of Azure. I would recommend trying an update to master if you need the fix urgently, otherwise it should be in our next release. You can see instructions on updating your deployment [here](https://www.tator.io/docs/administrator-guide/configuration/upgrading-tator) .

**Comment by jimmyfreese** [comment]
Thanks very much Jon.
