### ISSUE TITLE
Add better logging for failures in argo workflows (incl. ingestions)

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#84]
On a failure; it'd be nice if an alert caused a notification and the associated pods/pvcs were persistent for 48 hours.

**Comment by henxing** [comment]
On the ingestion side, the following code is an initial attempt at using `argo lint` to provide more useful parsing errors than just loading the yaml:
```
        # Try loading the manifest yaml and verify there are no YAML syntax errors
        result = subprocess.run(['argo', 'lint', manifest_path],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        if len(result.stderr) > 0:
            log_msg = f'Provided manifest file has the following errors'
            log_msg += result.stderr
            logging.error(log_msg)
            raise exc
```
However, it's not clear that this will work as-is. A cursory attempt to use this resulted in failure to parse a good workflow (due to template parameters) and failure to provide any meaningful error message when parsing invalid yaml. Respectively:

```
[hugh@ig11 mycode]$ argo lint feature_extraction_workflow.yaml
feature_extraction_workflow.yaml:
   ✖ in "feature-extraction" (Workflow): templates.pipeline.steps[0].worker templates.worker: failed to resolve {{workflow.parameters.media_ids}}
✖ 1 linting errors found!
```
and
```
[hugh@ig11 mycode]$ argo lint feature_extraction_workflow_bad_yaml.yaml
✖ found nothing to lint in the specified paths, failing...
```

**Comment by bctcvai** [comment]
This is largely resolved with the artifacts bucket.
